### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by benifunk** [G6EJD/ESP-Weather-Underground-Sensor-Upload#1]
Hi there,

your script is great. I tried to get it work for my home weather station. I failed like 100 times. 
It says that the connection failed. Is your script still running at your station?
I spent like 8 hours and did not get it to work. And I think that something with the authorization procedure does not work anymore. I read that you cannot use the pw anymore you have to use the key. 

My output:
[Connecting to   : rtupdate.wunderground.com
Requesting      : /weatherstation/updateweatherstation.php?ID=I90582621&PASSWORD=mykey&dateutc=now&tempf=81.73&humidity=45.86&dewptf=62.24&action=updateraw&realtime=1&rtfreq=60
Request sent    : Server Response : 
Status          : Closing connection
Error uploading to Weather Underground, trying next time
](url)

**Comment by benifunk** [comment]
So does it work anymore?

I would be really happy if you have an idea.

Greetings
Benjamin

**Comment by G6EJD** [comment]
WU were purchased by IBM and a condition of the buy-out was that they would no-longer allow free weather data downloads. The only way NOW is to pay their fee or if you had a PWS that was continuously uploading data then they give you a concession to download your own data. So effectively the WU service is shut. I have done most of the examples using Open Weather Map which is nearly identical and free. My PWS called imelksha2 is still uploading and so my code works, it’s no different from the published version

**Comment by benifunk** [comment]
Thank you so much for taking your time. Sad to hear. So thank you. I will try to work with open weather. Greetings

**Comment by evingston** [comment]
Hello, I am trying to mont this code on an ESP8286, but it gives error "Error uploading to Weather Underground, trying next time", is it still possible to use WU?

**Comment by G6EJD** [comment]
WU no-longer supports data uploads unless you have an active account and / or an active Personal Weather Station and you had an active account prior to the IBM takeover, after that date you have to pay $500/month to enable the access and enable uploads.
OpenWeatherMap remains a free service, but they don’t really support uploads.

**Comment by evingston** [comment]
sad new, then I cloud only used my station locally.

**Comment by jumper-d-1981** [comment]
okay...my google fu is slow but I get there eventually.  You can ignore the thing I posted in here.  I will look up your suggestion about open weather.

IBM always messing things up.  500 bucks to upload data to a community driven or previously community driven network is insane.

**Comment by G6EJD** [comment]
It’s still free if you maintain a personal weather station, but many didn’t keep their’s going post the takeover. I can still upload to mine.
